# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-27 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiAccountAnalyze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField()),
                ('contest_title', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='MultiAccountAnalyzeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('account_nick', models.CharField(max_length=100, null=True)),
                ('in_date', models.DateTimeField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='MAIN.MultiAccountAnalyze')),
            ],
        ),
        migrations.CreateModel(
            name='MultiIPAnalyze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField()),
                ('contest_title', models.CharField(max_length=255, null=True)),
                ('account_id', models.CharField(max_length=70)),
                ('account_nick', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='MultiIPAnalyzeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=70)),
                ('in_date', models.DateTimeField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='MAIN.MultiIPAnalyze')),
            ],
        ),
    ]
