# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-28 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0003_auto_20190227_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.IntegerField()),
                ('contest_id', models.IntegerField()),
                ('in_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='multiaccountanalyze',
            name='status',
        ),
        migrations.RemoveField(
            model_name='multiipanalyze',
            name='status',
        ),
    ]
