# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-28 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0004_auto_20190228_1050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='TaskTracking',
        ),
    ]
