# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-28 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0005_auto_20190228_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktracking',
            name='task_name',
            field=models.CharField(max_length=20),
        ),
    ]
