# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-28 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0006_auto_20190228_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktracking',
            name='task_name',
            field=models.CharField(max_length=50),
        ),
    ]
