- name: "Update The APT REPO"
  command: apt-get update
  #sudo: yes


- name: Install The Base deb software
  apt:
    name: "{{item}}"
  with_items:
    - python3
    - python3-pip
    - python3-dev
    - virtualenv
    - libmysqlclient-dev
    - python-mysqldb
  #sudo: yes


#- name: "Update The APT REPO"
#  command: virtualenv -p /usr/bin/python3 /app/virtualenv
#  sudo: yes



#- name: Initiate package in virtualenv
##  pip: 
#     virtualenv: /app/virtualenv
#     requirements: /app/ExaminationRegistrationSystem/requirements.txt
#     extra_args:  -i https://pypi.douban.com/simple
#       virtualenv_python=python3.5
       #requirements={{ app_dir }}/requirements.txt

 #   - git
 #   - libmysqld-dev
 #   - libmysqlclient-dev

#- name: Install the basic python packages
#  pip:
#    name: "{{item}}"
#    state: present
#  with_items:
#    - MySQL-python
#  sudo: yes
   

- name: Download the nodejs 10 install script
  get_url: 
    url: https://deb.nodesource.com/setup_10.x
    dest: /tmp/nodejs.sh
  #sudo: yes


- name: Run the nodejs script
  script: /tmp/nodejs.sh
  #sudo: yes


- name: Install nodejs 10
  apt:
    name: nodejs
  #sudo: yes


- name: Set taobao as nodejs registry
  command: npm config set registry https://registry.npm.taobao.org 
  #sudo: yes


- name: Install yarn package manager
  command: npm install -g yarn
  #sudo: yes

- name: Set taobao as yarn registry
  command: yarn config set registry https://registry.npm.taobao.org
  #sudo: yes

